version: "2"
services:
  mxprotocol-server:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configuration:/etc/mxprotocol-server
      - ./:/mxprotocol-server
    links:
      - postgresql
      - redis
      - mosquitto
    #environment:
    #  - TEST_POSTGRES_DSN=postgres://test:test@postgres/test?sslmode=disable
    #  - TEST_LORA_APP_SERVER=http://appserver:8080
    tty: true
    ports:
      - 4000:4000
    #security_opt:
    #  - seccomp:unconfined
    #cap_add:
    #  - SYS_PTRACE
  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:4-alpine

  mosquitto:
    image: eclipse-mosquitto
