version: "2"
services:
  mxprotocol-server:
    build: 
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./configuration:/etc/mxprotocol-server
      - ./:/mxprotocol-server
    links:
      - postgresql
      - redis
      - mosquitto
    environment:
      - APPSERVER=http://localhost:8080
      - MXPROTOCOL_SERVER=http://localhost:4000
    tty: true
    ports:
      - 4000:4000
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:5-alpine

  mosquitto:
    image: eclipse-mosquitto
