[general]
# Log level
#
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=5

# The number of times passwords must be hashed. A higher number is safer as
# an attack takes more time to perform.
password_hash_iterations=100000

host_server="localhost"
auth_server="http://appserver:8080"
auth_url="/api/internal/profile"

# PostgreSQL settings.
#
# Please note that PostgreSQL 9.5+ is required.
[postgresql]
# PostgreSQL dsn (e.g.: postgres://user:password@hostname/database?sslmode=disable).
#
# Besides using an URL (e.g. 'postgres://user:password@hostname/database?sslmode=disable')
# it is also possible to use the following format:
# 'user=loraserver dbname=loraserver sslmode=disable'.
#
# The following connection parameters are supported:
#
# * dbname - The name of the database to connect to
# * user - The user to sign in as
# * password - The user's password
# * host - The host to connect to. Values that start with / are for unix domain sockets. (default is localhost)
# * port - The port to bind to. (default is 5432)
# * sslmode - Whether or not to use SSL (default is require, this is not the default for libpq)
# * fallback_application_name - An application_name to fall back to if one isn't provided.
# * connect_timeout - Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
# * sslcert - Cert file location. The file must contain PEM encoded data.
# * sslkey - Key file location. The file must contain PEM encoded data.
# * sslrootcert - The location of the root certificate file. The file must contain PEM encoded data.
#
# Valid values for sslmode are:
#
# * disable - No SSL
# * require - Always SSL (skip verification)
# * verify-ca - Always SSL (verify that the certificate presented by the server was signed by a trusted CA)
# * verify-full - Always SSL (verify that the certification presented by the server was signed by a trusted CA and the server host name matches the one in the certificate)
dsn="postgres://postgres@postgres:5432/postgres?sslmode=disable"
automigrate=false

[redis]
url="redis://redis:6379"
max_idle=10
# Idle timeout.
#
# Close connections after remaining idle for this duration. If the value
# is zero, then idle connections are not closed. You should set
# the timeout to a value less than the server's timeout.
idle_timeout="5m0s"

# Automatically apply database migrations.
#
# It is possible to apply the database-migrations by hand
# (see https://github.com/brocaar/lora-app-server/tree/master/migrations)
# or let LoRa App Server migrate to the latest state automatically, by using
# this setting. Make sure that you always make a backup when upgrading Lora
# App Server and / or applying migrations.
automigrate=true

# This is the API and web-interface exposed to the end-user.
[application_server.http_server]
# ip:port to bind the (user facing) http server to (web-interface and REST / gRPC api)
bind=":4000"

# http server TLS certificate (optional)
tls_cert=""

# http server TLS key (optional)
tls_key=""

# JWT secret used for api authentication / authorization
# You could generate this by executing 'openssl rand -base64 32' for example
jwt_secret="DOE1KiNzpQ82elRQ9HMWyxmADQ5f2B2TBAgOjL7ZZWA="

# Allow origin header (CORS).
#
# Set this to allows cross-domain communication from the browser (CORS).
# Example value: https://example.com.
# When left blank (default), CORS will not be used.
cors_allow_origin="http://localhost:4000"

# when set, existing users can't be re-assigned (to avoid exposure of all users to an organization admin)"
disable_assign_existing_users=false

[supernode]
## For official Eth network
#contract_address="0x5Ca381bBfb58f0092df149bD3D243b08B9a8386e"
#supernode_address="0x8a96E17d85Bd897a88B547718865de990D2Fcb80"

## For Ether testnetwork (Ropsten)
contract_address="0xd0B0e864959d4625577939fC4d45b77aeB04F1d0"
supernode_address="0x63dF6a06D4a9e20199C6Be3eE9cac591b7d5D01F"

api_key="W8M6B92HBM7CUAQINJ8IMST29RY2ZVSQH4"
check_account_seconds=30
external_currency_abv="Ether"
ether_test_net=true

[paymentserver]
payment_service_address="payment"
payment_service_port=":2333"
